package uk.co.devfoundry.taskly.data.model

import java.util.UUID

/**
 * Represents a single to‐do item in Taskly.
 *
 * @param id         Unique identifier for the task (auto‐generated by default).
 * @param title      The user‐facing title or description of the task.
 * @param isComplete Whether the task has been marked complete.
 */
data class Task(
    val id: String = UUID.randomUUID().toString(),
    val title: String,
    val isComplete: Boolean = false
)
